import adminRoutes from './admin.routes.js';
import announcementRoutes from './announcement.routes.js';
import attendanceRoutes from './attendance.routes.js';
import authRoutes from './auth.routes.js';
import badgeRoutes from './badge.routes.js';
import collegeRoutes from './college.routes.js';
import courseRoutes from './course.routes.js';
import feedbackRoutes from './feedback.routes.js';
import gamificationRoutes from './gamification.routes.js';
import leaderboardRoutes from './leaderboard.routes.js';
import notificationRoutes from './notification.routes.js';
import productRoutes from './product.routes.js';
import purchaseRoutes from './purchase.routes.js';
import roleRoutes from './role.routes.js';
import studentRoutes from './student.routes.js';
import subjectRoutes from './subject.routes.js';
import teacherRoutes from './teacher.routes.js';
import transactionRoutes from './transaction.routes.js';
import userRoutes from './user.routes.js';
import walletRoutes from './wallet.routes.js';

export default (app) => {
    app.use('/api/admin', adminRoutes);
    app.use('/api/announcements', announcementRoutes);
    app.use('/api/attendance', attendanceRoutes);
    app.use('/api/auth', authRoutes);
    app.use('/api/badges', badgeRoutes);
    app.use('/api/colleges', collegeRoutes);
    app.use('/api/courses', courseRoutes);
    app.use('/api/feedback', feedbackRoutes);
    app.use('/api/gamification', gamificationRoutes);
    app.use('/api/leaderboard', leaderboardRoutes);
    app.use('/api/notifications', notificationRoutes);
    app.use('/api/products', productRoutes);
    app.use('/api/purchases', purchaseRoutes);
    app.use('/api/roles', roleRoutes);
    app.use('/api/students', studentRoutes);
    app.use('/api/subjects', subjectRoutes);
    app.use('/api/teachers', teacherRoutes);
    app.use('/api/transactions', transactionRoutes);
    app.use('/api/users', userRoutes);
    app.use('/api/wallet', walletRoutes);
};